### ISSUE TITLE
An error occurred while using the softmax,CUDNNError: CUDNN_STATUS_BAD_PARAM (code 3)

### ISSUE THREAD

**Issue by yeruoforever** [FluxML/NNlib.jl#285]
```julia
using CUDA
using Flux

x=CUDA.rand(2,3,4,5)
softmax(x)
softmax(x;dims=1)
softmax(x;dims=2)
softmax(x;dims=3)
softmax(x;dims=4)
```
When dims is equal to 1 and 2, it works well. But when dims is greater than 2, the above error occurs.

**Comment by CarloLucibello** [comment]
probably it's not supported by cudnn, we have to fallback to julia implementation for `dims>2`

**Comment by CarloLucibello** [comment]
The issue has been fixed with the introduction of NNlibCUDA.jl
